### ISSUE TITLE
Need Example Code 

### ISSUE THREAD

**Issue by Arrow66** [MarekLabuz/lets-paginate#1]
Hi,
I'm kinda new to redux .trying to understand your example snippets in the read me .Couldn't make it work . I'm stuck at this step 
`import { reduxPagination } from 'lets-paginate'
// ...
export default reduxPagination({
  names: ['users'],
  fetch: [getUsers],
  allDataExpected: [true] // default - false
}, mapStateAndDispatchToProps)(Users)`

if possible can you  provide example code .it'll  be really useful for beginners 

thanks

**Comment by MarekLabuz** [comment]
Hi,
I'm glad that you are interested in my project. However, it is no longer maintained, as the last commit was in 2017. Since then, a lot has changed in the world of React/Redux applications. I recommend you to look for some up-to-date examples and libraries. I should have archived this repository much earlier.
